"""
applicants/resume_parser.py — Parse structured data from LaTeX resume files
=============================================================================
Extracts work experience from tex files generated by the resume builder.
Reusable across all applicant types.
"""

import re
from pathlib import Path


def parse_resume_tex(pdf_path: Path) -> dict:
    """Parse work experience from a resume tex file.

    Args:
        pdf_path: Path to the resume PDF (tex file is found by changing extension).

    Returns:
        Dict with key: work_experience (list).

    Raises:
        ValueError: If tex file not found or required data cannot be parsed.
    """
    tex_path = pdf_path.with_suffix(".tex")
    if not tex_path.exists():
        raise ValueError(f"Tex file not found: {tex_path}")
    content = tex_path.read_text()

    exp_section = _extract_tex_section(content, "Experience")

    heading_pattern = r'\\resumeSubheading\s*'

    work_experience = []
    if exp_section:
        for pos in [m.start() for m in re.finditer(heading_pattern, exp_section)]:
            args = _extract_brace_args(exp_section[pos:], 4)
            if len(args) < 4:
                continue
            company, location, title, dates = args
            start, end = _parse_date_range(dates)
            # Extract resumeItem contents after this heading
            next_heading = re.search(heading_pattern, exp_section[pos + 1:])
            block_end = pos + 1 + next_heading.start() if next_heading else len(exp_section)
            block = exp_section[pos:block_end]
            items = _extract_resume_items(block)
            description = " ".join(_strip_latex(item) for item in items)
            work_experience.append({
                "jobTitle": title,
                "companyName": company,
                "location": location,
                "startDate": start,
                "endDate": end,
                "currentlyWorkHere": "present" in end.lower(),
                "roleDescription": description,
            })

    if not work_experience:
        raise ValueError("Could not parse any work experience from resume tex file")

    return {"work_experience": work_experience}


def _extract_tex_section(content: str, section_name: str) -> str:
    """Extract content between \\section{name} and the next \\section."""
    pattern = rf'\\section\{{{section_name}\}}(.*?)(?=\\section\{{|\\end\{{document\}})'
    match = re.search(pattern, content, re.DOTALL)
    return match.group(1) if match else ""


def _extract_brace_args(text: str, count: int) -> list[str]:
    """Extract {arg1}{arg2}... from text, handling nested braces."""
    args = []
    i = text.find("{")
    while i != -1 and len(args) < count:
        depth = 0
        start = i + 1
        for j in range(i, len(text)):
            if text[j] == "{":
                depth += 1
            elif text[j] == "}":
                depth -= 1
                if depth == 0:
                    args.append(text[start:j])
                    i = text.find("{", j + 1)
                    break
        else:
            break
    return args


def _extract_resume_items(block: str) -> list[str]:
    """Extract all \\resumeItem{...} contents from a block, handling nested braces."""
    items = []
    for match in re.finditer(r'\\resumeItem\{', block):
        start = match.end()
        depth = 1
        for j in range(start, len(block)):
            if block[j] == "{":
                depth += 1
            elif block[j] == "}":
                depth -= 1
                if depth == 0:
                    items.append(block[start:j])
                    break
    return items


def _strip_latex(text: str) -> str:
    """Remove LaTeX commands from text, keeping content."""
    text = re.sub(r'\\(?:textbf|textit|emph|underline)\{([^}]*)\}', r'\1', text)
    text = re.sub(r'\\href\{[^}]*\}\{([^}]*)\}', r'\1', text)
    text = re.sub(r'\\[a-zA-Z]+\{([^}]*)\}', r'\1', text)
    text = re.sub(r'\\[a-zA-Z]+', '', text)
    text = text.replace("\\%", "%").replace("~", " ").replace("$|$", "|")
    text = re.sub(r'\s+', ' ', text).strip()
    return text


def _parse_date_range(dates: str) -> tuple[str, str]:
    """Parse 'June 2024 -- Oct 2025' into ('06/2024', '10/2025')."""
    months = {
        "jan": "01", "feb": "02", "mar": "03", "apr": "04",
        "may": "05", "jun": "06", "jul": "07", "aug": "08",
        "sep": "09", "oct": "10", "nov": "11", "dec": "12",
        "january": "01", "february": "02", "march": "03", "april": "04",
        "june": "06", "july": "07", "august": "08", "september": "09",
        "october": "10", "november": "11", "december": "12",
    }
    parts = re.split(r'\s*--\s*', dates.strip())
    if len(parts) != 2:
        raise ValueError(f"Could not parse date range: '{dates}'")

    results = []
    for part in parts:
        part = part.strip()
        if part.lower() == "present":
            results.append("present")
            continue
        m = re.match(r'(\w+)\s+(\d{4})', part)
        if not m:
            raise ValueError(f"Could not parse date: '{part}'")
        month_str, year = m.groups()
        month_num = months.get(month_str.lower())
        if not month_num:
            raise ValueError(f"Unknown month: '{month_str}'")
        results.append(f"{month_num}/{year}")

    return results[0], results[1]
